config/routes.rb
Phd::Application.routes.draw do
  
  devise_for :users, skip: :registerable, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'

get 'folders/search', to: 'folders#search'
post 'folders/search', to: 'folders#search_index'
patch 'folders/:id/upload_avatar', to:'folders#upload_avatar'
resources :folders

end

app/models/diocese.rb
class Diocese < ActiveRecord::Base
  has_many :folders, foreign_key: 'dioceseId', after_add: [ lambda { |d,f| f.__elasticsearch__.index_document}],
                                               after_remove: [ lambda { |d,f| f.__elasticsearch__.index_document}]
end

app/models/dissertation.rb
class Dissertation < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
  has_one :mentor, :class_name => "Folder", :foreign_key => "folderId", :primary_key => 'mentorId'
  has_and_belongs_to_many :keywords, :join_table => "dissertations_keywords", :foreign_key => "dissertationId", :association_foreign_key => 'keywordId'
end

app/models/dissertations_keywords.rb
class DissertationsKeywords < ActiveRecord::Base
  belongs_to :dissertation, :foreign_key => "dissertationId"
  belongs_to :keyword, :foreign_key => "keywordId"
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId"
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
end

app/models/folder.rb
require "elasticsearch/model"
class Folder < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name "folders-#{Rails.env}"

  after_touch { index_document }
  after_save  { index_document }

  has_many :dissertations, :foreign_key => "folderId", after_add: [ lambda { |f,l| f.index_document } ],
                                                       after_remove: [ lambda { |f,l| f.index_document } ]
  has_many :educations, :foreign_key => "folderId", after_add: [ lambda { |f,l| f.index_document } ],
                                                    after_remove: [ lambda { |f,l| f.index_document } ]
  has_many :experiences, :foreign_key => "folderId", after_add: [ lambda { |f,l| f.index_document } ],
                                                     after_remove: [ lambda { |f,l| f.index_document } ]
  has_many :language_knowledges, :foreign_key => "folderId", dependent: :delete_all
  has_many :languages, through: :language_knowledges, after_add: [ lambda { |f,l| f.index_document } ],
                                                      after_remove: [ lambda { |f,l| f.index_document } ]
  has_many :ordinations, :foreign_key => "folderId"
  has_many :phones, :foreign_key => "folderId"
  has_many :emails, :foreign_key => "folderId"
  has_many :publications, :foreign_key => "folderId"

  belongs_to :diocese, :foreign_key => "dioceseId"
  belongs_to :monk_community, :foreign_key => "monkCommunityId"

  def full_name
    return firstName + ' ' + lastName
  end

  def full_name=(full_name)
    prefix, first_name, last_name = full_name.matches(/^(.*\s?)([A-ZАБВГҐДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЮЯ].+)\s(.+)$/).captures unless full_name.length == 0
    @firstName = firstName
    @lastName = last_name
  end

  def index_document
    __elasticsearch__.index_document
  end

  def as_indexed_json(options={})
    self.as_json(
      except: [:dateCreated, :dateUpdated, :dioceseId],
      include: {
        diocese: { only: :name },
        dissertations: { only:  [ :title, :educationLevel, :educationPlace, :notes ], include: { keywords: { only: :name }}},
        educations: { only: [:place, :educationLevel ]},
        experiences: { only: [:place, :position ]},
        language_knowledges: { only: :level, include: { language: { only: :name }}},
        monk_community: { only: :name },
        publications: { only: :name }
      }
    )
  end
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  has_and_belongs_to_many :dissertations, :join_table => "dissertations_keywords", :foreign_key => "keywordId", association_foreign_key: 'dissertationId'
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :language_knowledges, :foreign_key => "languageId"
  has_many :folders, :through => :language_knowledges
  after_update { self.language_knowledges.each(&:touch) }
  after_destroy { |lang| update_folder_index(lang) }
  before_destroy { |lang| save_folder_id(lang) }

  private
    def save_folder_id(lang)
      @folders = lang.folders
    end

    def update_folder_index(lang)
      LanguageKnowledge.delete_all(languageId: lang.languageId)
      @folders.each do |folder|
        folder.reload
        folder.__elasticsearch__.index_document
      end
    end
end

app/models/language_knowledge.rb
class LanguageKnowledge < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
  belongs_to :language, :foreign_key => "languageId"
end

app/models/monk_community.rb
class MonkCommunity < ActiveRecord::Base
  has_many :folders, :foreign_key => 'monkCommunityId'
end

app/models/ordination.rb
class Ordination < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId"
  has_one :bishop, class_name: "Folder", primary_key: "bishopId", foreign_key: 'folderId'
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId"
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
          :validatable
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authenticate_user!

  def upload_avatar
    @resource = Folder.find params[:id]
    @resource.avatar_url = params[:folder][:avatar_url]
    @resource.save
    redirect_to folder_path(params[:id])
  end

  def index
    @resource = Folder.all
    @tabs = { search: nil, result: 1 }
    render 'resource'
  end

  def show
    @resource = Folder.find(params[:id])
    @tabs = { search: nil, result_details: 1 }
    render 'resource'
  end

  def search
    @tabs = { search: 1, result: nil }
    render 'resource'
  end

  def search_index
    @tabs = { search: nil, result: 1 }
    search_response = Folder.search params[:search]
    @resource = []
    @resource = search_response.records.to_a if search_response.records.total > 0
    render 'resource'
  end
end

app/controllers/stubs_controller.rb
class StubsController < ApplicationController
  def login
  end

  def search
  end

  def result
    @folder = Folder.first
  end

  def result_detail
    @email = Email.first
    @folder = Folder.find(@email.folderId) 
    render 'erorr no data' if @folder.nil?
  end

  def action
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folder_helper.rb
module FolderHelper
  def phone_description(description)
    if description.nil?
      return 'folder.contact.phones.phone'
    else
      return "folder.contact.phones.#{description}"
    end
  end
end

app/helpers/stubs_helper.rb
module StubsHelper
  def active_class(is_active)
    if is_active
      return 'active_result'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/stubs/_tabs.html.haml
%ul.nav.nav-tabs.margin-top-20
  %li.active{role: "presentation"}
    %a{:href => "#one", role: 'tab', 'data-toggle' => 'tab', 'aria-controls' => 'one'}
      = t('search')
  %li{role: "presentation"}
    %a{:href => "#two", role: 'tab', 'data-toggle' => 'tab', 'aria-controls' => 'two'}
      = t('load_single_data_file')
  %li{role: "presentation"}
    %a{:href => "#three", role: 'tab', 'data-toggle' => 'tab', 'aria-controls' => 'three'}
      = t('load_multiple_data_file')

app/views/stubs/_tabs_result.html.haml
%ul.nav.nav-tabs.margin-top-20
  %li{role: "presentation"}
    %a{:href => "#one", role: 'tab', 'data-toggle' => 'tab', 'aria-controls' => 'one'}
      = t('search')
  %li{role: "presentation"}
    %a{:href => "#two", role: 'tab', 'data-toggle' => 'tab', 'aria-controls' => 'two'}
      = t('load_single_data_file')
  %li{role: "presentation"}
    %a{:href => "#three", role: 'tab', 'data-toggle' => 'tab', 'aria-controls' => 'three'}
      = t('load_multiple_data_file')
  %li.active{role: "presentation"}
    %a{:href => "#result", role: 'tab', 'data-toggle' => 'tab', 'aria-controls' => 'result'}
      = t('search_result')

app/views/stubs/action.html.haml
.well
  hello there

app/views/stubs/result.html.haml
.tab-panel
  = render 'tabs_result'
  .container
  .tab-content
    = render 'stubs/tabs/one'
    = render 'stubs/tabs/two'
    = render 'stubs/tabs/three'
    = render 'stubs/tabs/result'

app/views/stubs/result_detail.html.haml
.tab-panel
  = render 'tabs_result'
  .container
  .tab-content
    = render 'stubs/tabs/one'
    = render 'stubs/tabs/two'
    = render 'stubs/tabs/three'
    = render 'stubs/tabs/result_details', object: @folder

app/views/stubs/result_details/_dissertations.html.haml
.col-sm-10.col-sm-offset-1.col-xs-12.col-xs-offset-0
  .row.margin-top-20
    .col-xs-11.cols-xs-offset-1
      .panel.panel-success
        .panel-heading
          = t 'folder.dissertations.title'
        .panel-body
          - if locals[:dissertations].length
            %table.table.table-condensed.table-striped.table-bordered
              %tbody
                - locals[:dissertations].each do |dissertation|
                  %tr
                    %th.col-xs-3
                      = t('folder.dissertations.years')
                    %th.col-xs-3
                      = t 'folder.dissertations.approvment_date'
                    %th
                      = t 'folder.dissertations.title'
                  %tr
                    %td
                      = l dissertation.startDate, format: :years
                      &dash;
                      = l dissertation.finishDate, format: :years
                      = ' ' + t('yy')
                    %td
                      = [l(dissertation.thesisDate, format: :day), t(:'date.month_names')[l(dissertation.thesisDate, format: :month).to_i], l(dissertation.thesisDate, format: :years), t('y')].join(' ')
                    %td
                      = dissertation.title
                  %tr
                    %th{ colspan: '2' }
                      = t 'folder.dissertations.level'
                    %th 
                      = t 'folder.dissertations.mentor'
                  %tr
                    %td{ colspan: '2' }
                      = t dissertation.educationLevel
                    %td
                      - mentor = dissertation.mentor
                      - education_place = dissertation.educationPlace
                      = mentor.lastName + ' ' + mentor.firstName + ', ' + education_place
                  %tr
                    %th{ colspan: '2' }
                      = t 'folder.dissertations.keywords'
                    %th
                      = t 'folder.dissertations.notes'
                  %tr
                    %td{ colspan: '2' }
                      - if dissertation.keywords.length 
                        - keywords = []
                        - dissertation.keywords.each do |keyword|
                          - keywords.push(keyword.name)
                        = keywords.join(', ')
                    %td
                      = dissertation.notes
          - else
            = t 'no_data'

app/views/stubs/result_details/_education.html.haml
.col-sm-10.col-sm-offset-1.col-xs-12.col-xs-offset-0
  .row.margin-top-40
    .col-xs-11.cols-xs-offset-1
      .panel.panel-success
        .panel-heading
          = t 'folder.education.title'
        .panel-body
          -if locals[:educations].length
            %table.table.table-condensed.table-striped
              %thead
                %tr
                  %th.col-xs-3
                    = t('folder.education.years')
                  %th.col-xs-3
                    = t 'folder.education.place'
                  %th
                    = t 'folder.education.level'
              %tbody
                - locals[:educations].each do |education|
                  %tr
                    %td
                      = l education.startDate, format: :years
                      &dash;
                      = l education.endDate, format: :years
                      = ' ' + t('yy')
                    %td
                      = education.place
                    %td
                      = t education.educationLevel
          - else
            = t 'no_data'

app/views/stubs/result_details/_experiences.html.haml
.col-sm-10.col-sm-offset-1.col-xs-12.col-xs-offset-0
  .row.margin-top-20
    .col-xs-11.cols-xs-offset-1
      .panel.panel-success
        .panel-heading
          = t 'folder.experience.title'
        .panel-body
          -if locals[:experiences].length
            %table.table.table-condensed.table-striped
              %thead
                %tr
                  %th.col-xs-2
                    = t('folder.experience.years')
                  %th.col-xs-5
                    = t 'folder.experience.name'
                  %th
                    = t 'folder.experience.position'
              %tbody
                - locals[:experiences].each do |experience|
                  %tr
                    %td
                      = l experience.startDate, format: :years
                      &dash;
                      = l experience.endDate, format: :years
                      = ' ' + t('yy')
                    %td
                      = experience.place
                    %td
                      = experience.position
          - else
            = t 'no_data'

app/views/stubs/result_details/_languages.html.haml
.col-sm-10.col-sm-offset-1.col-xs-12.col-xs-offset-0
  .row.margin-top-20
    .col-xs-11.cols-xs-offset-1
      .panel.panel-success
        .panel-heading
          = t 'folder.foreign_language.title'
        .panel-body
          - if locals[:languages].length
            %table.table.table-condensed
              %tbody
                - locals[:languages].each do |language|
                  %tr
                    %td{style: 'border:none;'}
                      - knowledge = locals[:lang_knowledges].select{|knowledge| knowledge["languageId"] == language.languageId }
                      = language.name + '(' + knowledge[0][:level] + ')'
          - else
            = t 'no_data'

app/views/stubs/result_details/_note.html.haml
.col-sm-10.col-sm-offset-1.col-xs-12.col-xs-offset-0
  .row.margin-top-20
    .col-xs-11.cols-xs-offset-1
      .panel.panel-success
        .panel-heading
          = t 'folder.note.title'
        .panel-body
          - if !locals[:note].nil?
            %table.table.table-condensed
              %tbody
                %tr
                  %td{style: 'border:none;'}
                    = locals[:note]
          - else
            = t 'no_data'

app/views/stubs/result_details/_ordination_row.html.haml
%tr
  %td.text-right{style: 'border: 0'}
    %h4{style: 'line-height: 10%;'}
      %strong
        = t('folder.ordination.' + locals[:ordination].ordinationType) + ':'
  %td
    = [l(locals[:ordination].date, format: :day), t(:'date.month_names')[l(locals[:ordination].date, format: :month).to_i], l(locals[:ordination].date, format: :years), t('y')].join(' ')
  %td
    = t('cur') + ' ' + locals[:ordination].bishop.firstName + ' ' + locals[:ordination].bishop.lastName

app/views/stubs/result_details/_publications.html.haml
.col-sm-10.col-sm-offset-1.col-xs-12.col-xs-offset-0
  .row.margin-top-20
    .col-xs-11.cols-xs-offset-1
      .panel.panel-success
        .panel-heading
          = t 'folder.publications.title'
        .panel-body
          - if locals[:publications].length
            %table.table.table-condensed.table-striped
              %tbody
                - i = 0
                - locals[:publications].each do |publication|
                  %tr
                    %td
                      = i += 1;
                      = publication.name + ', ' + [l(publication.date, format: :day), t(:'date.month_names')[l(publication.date, format: :month).to_i], l(publication.date, format: :years), t('y')].join(' ')
          - else
            = t 'no_data'

app/views/stubs/result_details/_row.html.haml
.row
  .col-sm-4.col-sm-offset-1.text-right.col-xs-6
    %strong
      = I18n.t(locals[:label]) + ':'
  .col-sm-4.col-xs-6
    = locals[:data]

app/views/stubs/result_details/_small_row.html.haml
.row
  .col-sm-3.col-xs-6{style: 'text-align: right;'}
    %h4{style: 'margin: 3px 0;'}
      %strong
        = t(locals[:label]) + ":"
  .col-sm-6.cols-xs-6{style: 'padding: 0.3em 0;'}
    %span
      = locals[:data]

app/views/stubs/search.html.haml
.tab-panel
  = render 'tabs'
  .container
  .tab-content
    = render 'stubs/tabs/one'
    = render 'stubs/tabs/two'
    = render 'stubs/tabs/three'

app/views/stubs/tabs/_one.html.haml
#one.tab-pane{role: 'tabpanel'}
  = form_tag folders_search_path, class: ['form-inline', 'margin-top-40', 'col-sm-8', 'col-sm-offset-2', 'col-xs-offset-0', 'text-center'] do
    .form-group.col-xs-12.col-sm-12
      = text_field_tag 'searchsting', '', style: 'width: 80%; margin: 0 auto;', class: 'form-control'
    .form-group.margin-top-20
      %submit.btn.btn-success{:type => 'button', :style => 'width: 30%'}
        = t('search')

app/views/stubs/tabs/_result.html.haml
#result.tab-pane.active{role: 'tabpanel'}
  %h3
    %strong
      = t('search_result') + ':'
  - unless locals[:folders].nil?
    - locals[:folders].each do |folder|
      - unless(folder.firstName.nil? and folder.lastName.nil?)
        = render 'folders/results/result_item', locals: {folder: folder}
  - else 
    = t 'no_data'

app/views/stubs/tabs/_result_details.html.haml
#result.tab-pane.active{role: 'tabpanel'}
  .margin-top-40
    .row
      .col-lg-2.col-md-3.col-sm-4.col-xs-12
        %img{:src => "#", :alt => "this is image with 200 pixels dimention", width: '200', height: '200'}/
      .col-lg-9.col-lg-offset-1.col-md-9.col-sm-8.col-xs-12
        = render 'stubs/result_details/small_row', locals: { label: 'folder.first_name', data: @folder.firstName }
        = render 'stubs/result_details/small_row', locals: { label: 'folder.last_name', data: @folder.lastName }
        = render 'stubs/result_details/small_row', locals: { label: 'folder.sex', data: @folder.sex }
        = render 'stubs/result_details/small_row', locals: { label: 'folder.diocese', data: @folder.diocese.name }
        = render 'stubs/result_details/small_row', locals: { label: 'folder.monkCommunity', data: @folder.monk_community.name }
        = render 'stubs/result_details/small_row', locals: { label: 'folder.perpetualVowsDate', data: [l(@folder.perpetualVowsDate, format: :day), t(:'date.month_names')[l(@folder.perpetualVowsDate, format: :month).to_i], l(@folder.perpetualVowsDate, format: :years), t('y')].join(' ') }
    .row
      .col-sm-9.col-sm-offset-1.margin-top-20
        %table.table.table-stripped
          %thead
            %tr
              %th.text-center{style: 'width: 8%'}
                %h3
                  %strong
                    = t 'folder.ordination.name'
              %th.text-center{style: 'width: 20%'}
                %strong
                  = t 'folder.ordination.date'
              %th.text-center
                %strong
                  = t 'folder.ordination.ordinator'
            %tbody
              - @folder.ordinations.each do |ordination|
                = render 'stubs/result_details/ordination_row', locals: {ordination: ordination}
    = render '/stubs/result_details/row', locals: { label: 'folder.contact.address', data: @folder.address}
    - @folder.phones.each do |phone|
      = render '/stubs/result_details/row', locals: { label: phone.description, data: phone.phoneNumber }
    - @folder.emails.each do |email|
      = render '/stubs/result_details/row', locals: { label: 'folder.contact.email', data: email.email }
    = render '/stubs/result_details/row', locals: { label: 'folder.contact.web_page', data: @folder.webPage }
    = render '/stubs/result_details/education', locals: { educations: @folder.educations }
    = render '/stubs/result_details/dissertations', locals: { dissertations: @folder.dissertations }
    = render '/stubs/result_details/experiences', locals: { experiences: @folder.experiences }
    = render '/stubs/result_details/publications', locals: { publications: @folder.publications }
    = render '/stubs/result_details/languages', locals: { languages: @folder.languages, lang_knowledges: @folder.language_knowledges }
    = render '/stubs/result_details/note', locals: { note: @folder.note }
    .row
      .col-sm-9.col-sm-offset-1
        .margin-top-40.text-center
          .col-sm-6
            %h3{ style: 'display: inline-block;'}
              %strong
                = t 'date.title'
            .date{ style: 'border-bottom: 1px solid grey; display: inline-block; margin-left: 10px;'}
              - time = Time.now
              = [l(time, format: :day), t(:'date.month_names')[l(time, format: :month).to_i], l(time, format: :years), t('y')].join(' ')
          .col-sm-6
            %h3{ style: 'display: inline-block;'}
              %strong
                = t 'sign'
            .sign{ style: 'border-bottom: 1px solid grey; display: inline-block; margin-left: 10px;'}
              = @folder.firstName + ' ' + @folder.lastName
    .row.margin-top-40
      .col-sm-9.col-sm-offset-1
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis, aspernatur ullam eos voluptatem blanditiis libero explicabo similique! Accusantium iusto recusandae quia cumque debitis sed dolorem veritatis, laudantium unde nesciunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis, aspernatur ullam eos voluptatem blanditiis libero explicabo similique! Accusantium iusto recusandae quia cumque debitis sed dolorem veritatis, laudantium unde nesciunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis, aspernatur ullam eos voluptatem blanditiis libero explicabo similique! Accusantium iusto recusandae quia cumque debitis sed dolorem veritatis, laudantium unde nesciunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis, aspernatur ullam eos voluptatem blanditiis libero explicabo similique! Accusantium iusto recusandae quia cumque debitis sed dolorem veritatis, laudantium unde nesciunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis, aspernatur ullam eos voluptatem blanditiis libero explicabo similique! Accusantium iusto recusandae quia cumque debitis sed dolorem veritatis, laudantium unde nesciunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis, aspernatur ullam eos voluptatem blanditiis libero explicabo similique! Accusantium iusto recusandae quia cumque debitis sed dolorem veritatis, laudantium unde nesciunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda debitis, aspernatur ullam eos voluptatem blanditiis libero explicabo similique! Accusantium iusto recusandae quia cumque debitis sed dolorem veritatis, laudantium unde nesciunt.

app/views/stubs/tabs/_three.html.haml
#three.tab-pane{role: 'tabpanel'}
  here we have upload all info 

app/views/stubs/tabs/_two.html.haml
#two.tab-pane{role: 'tabpanel'}
  here we have upload one data panels

app/views/welcome/index.html.haml
%h1
  = t 'wellcome'