config/routes.rb
Phd::Application.routes.draw do
  
  devise_for :users, skip: :registerable, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'

get 'folders/search', to: 'folders#search'
post 'folders/search', to: 'folders#search_index'
patch 'folders/:id/upload_avatar', to:'folders#upload_avatar'
resources :folders

end

app/models/diocese.rb
class Diocese < ActiveRecord::Base
  has_many :folders, foreign_key: 'dioceseId', after_add: [ lambda { |d,f| f.__elasticsearch__.index_document}],
                                               after_remove: [ lambda { |d,f| f.__elasticsearch__.index_document}]
end

app/models/dissertation.rb
class Dissertation < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
  has_one :mentor, :class_name => "Folder", :foreign_key => "folderId", :primary_key => 'mentorId'
  has_and_belongs_to_many :keywords, :join_table => "dissertations_keywords", :foreign_key => "dissertationId", :association_foreign_key => 'keywordId'
end

app/models/dissertations_keywords.rb
class DissertationsKeywords < ActiveRecord::Base
  belongs_to :dissertation, :foreign_key => "dissertationId"
  belongs_to :keyword, :foreign_key => "keywordId"
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId"
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
end

app/models/folder.rb
require "elasticsearch/model"
class Folder < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name "folders-#{Rails.env}"

  after_touch { index_document }
  after_save  { index_document }

  has_many :dissertations, :foreign_key => "folderId", after_add: [ lambda { |f,l| f.index_document } ],
                                                       after_remove: [ lambda { |f,l| f.index_document } ]
  has_many :educations, :foreign_key => "folderId", after_add: [ lambda { |f,l| f.index_document } ],
                                                    after_remove: [ lambda { |f,l| f.index_document } ]
  has_many :experiences, :foreign_key => "folderId", after_add: [ lambda { |f,l| f.index_document } ],
                                                     after_remove: [ lambda { |f,l| f.index_document } ]
  has_many :language_knowledges, :foreign_key => "folderId", dependent: :delete_all
  has_many :languages, through: :language_knowledges, after_add: [ lambda { |f,l| f.index_document } ],
                                                      after_remove: [ lambda { |f,l| f.index_document } ]
  has_many :ordinations, :foreign_key => "folderId"
  has_many :phones, :foreign_key => "folderId"
  has_many :emails, :foreign_key => "folderId"
  has_many :publications, :foreign_key => "folderId"

  belongs_to :diocese, :foreign_key => "dioceseId"
  belongs_to :monk_community, :foreign_key => "monkCommunityId"

  def full_name
    return firstName + ' ' + lastName
  end

  def full_name=(full_name)
    prefix, first_name, last_name = full_name.matches(/^(.*\s?)([A-ZАБВГҐДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЮЯ].+)\s(.+)$/).captures unless full_name.length == 0
    @firstName = firstName
    @lastName = last_name
  end

  def index_document
    __elasticsearch__.index_document
  end

  def as_indexed_json(options={})
    self.as_json(
      except: [:dateCreated, :dateUpdated, :dioceseId],
      include: {
        diocese: { only: :name },
        dissertations: { only:  [ :title, :educationLevel, :educationPlace, :notes ], include: { keywords: { only: :name }}},
        educations: { only: [:place, :educationLevel ]},
        experiences: { only: [:place, :position ]},
        language_knowledges: { only: :level, include: { language: { only: :name }}},
        monk_community: { only: :name },
        publications: { only: :name }
      }
    )
  end
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  has_and_belongs_to_many :dissertations, :join_table => "dissertations_keywords", :foreign_key => "keywordId", association_foreign_key: 'dissertationId'
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :language_knowledges, :foreign_key => "languageId"
  has_many :folders, :through => :language_knowledges
  after_update { self.language_knowledges.each(&:touch) }
  after_destroy { |lang| update_folder_index(lang) }
  before_destroy { |lang| save_folder_id(lang) }

  private
    def save_folder_id(lang)
      @folders = lang.folders
    end

    def update_folder_index(lang)
      LanguageKnowledge.delete_all(languageId: lang.languageId)
      @folders.each do |folder|
        folder.reload
        folder.__elasticsearch__.index_document
      end
    end
end

app/models/language_knowledge.rb
class LanguageKnowledge < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
  belongs_to :language, :foreign_key => "languageId"
end

app/models/monk_community.rb
class MonkCommunity < ActiveRecord::Base
  has_many :folders, :foreign_key => 'monkCommunityId'
end

app/models/ordination.rb
class Ordination < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId"
  has_one :bishop, class_name: "Folder", primary_key: "bishopId", foreign_key: 'folderId'
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId"
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :folder, :foreign_key => "folderId", touch: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
          :validatable
end

app/controllers/stubs_controller.rb
class StubsController < ApplicationController
  def login
  end

  def search
  end

  def result
    @folder = Folder.first
  end

  def result_detail
    @email = Email.first
    @folder = Folder.find(@email.folderId) 
    render 'erorr no data' if @folder.nil?
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folder_helper.rb
module FolderHelper
  def phone_description(description)
    if description.nil?
      return 'folder.contact.phones.phone'
    else
      return "folder.contact.phones.#{description}"
    end
  end
end

app/helpers/stubs_helper.rb
module StubsHelper
  def active_class(is_active)
    if is_active
      return 'active_result'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Phd
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar.navbar-default.navbar-static-top
      .container-fluid
        .navbar-header
          %button.navbar-toggle{type: 'button', 'data-toggle' => 'collapse', 'data-target' => '.navbar-collapse'}
            %span.sr-only
              = t 'toggle_navigation'
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => ""}
            = I18n.t('almanackh')
        %ul.nav.navbar-nav.navbar-right.collapse.navbar-collapse
          - if user_signed_in?
            %li
              = link_to folders_path do
                = t 'all'
            %li
              = link_to destroy_user_session_path, method: :delete do
                = t 'logout'
          - else
            %li
              = link_to new_user_session_path do
                = t 'login.name'
    .container
      .row
        .text-center
          %p.text-success
            = notice
          %p.text-danger
            = alert
        = yield
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = filepicker_js_include_tag
    = render 'tracking/hotjar'

app/views/tracking/_hotjar.html.haml
:javascript
  (function(f,b){
    var c;
    f.hj=f.hj||function(){(f.hj.q=f.hj.q||[]).push(arguments)};
    f._hjSettings={hjid:39715, hjsv:4};
    c=b.createElement("script");c.async=1;
    c.src="//static.hotjar.com/c/hotjar-"+f._hjSettings.hjid+".js?sv="+f._hjSettings.hjsv;
    b.getElementsByTagName("head")[0].appendChild(c); 
  })(window,document);
/ %script{type: 'text/javascript'}